### ISSUE TITLE
Refreshing page with non-existent user sets session cookie to `undefined`

### ISSUE THREAD

**Issue by neboman11** [gatsby-tv/gatsby#26]
If I log in to Gatsby and then delete the user in the database, refreshing the page causes the session cookie to be set to `undefined`. This prevents me from logging in with any account since it seems to use the existing session token (even if it's for a different account) to log me in. This of course causes westegg to throw a `malformedJsonWebTokenError`.

**Comment by cjayross** [comment]
So the way it works is that the app uses local storage to store the session token. Every time the app loads, if there is a token in local storage, the app will check if that token is valid.

I think I can see how this could happen, should be an easy fix.

**Comment by cjayross** [comment]
I'm pretty sure this recent commit should have fixed this. Keep in mind that the session isn't stored in a cookie, it is stored in local storage and having the session set to `undefined` is expected behavior whenever you are signed out.
