### ISSUE TITLE
Video play/pause overlay shows after buffering completes on mobile

### ISSUE THREAD

**Issue by neboman11** [gatsby-tv/gatsby#38]
If a video buffers while you are watching it on mobile, after the video finishes loading the next chunk, it displays the play/pause overlay.

**Comment by cjayross** [comment]
Shoot. Yeah, this is a problem.

**Comment by cjayross** [comment]
Ok, so I believe the change I added fixes this, but unfortunately this is a hard situation to replicate reliably.

**Comment by neboman11** [comment]
Confirmed this is fixed
