### ISSUE TITLE
Refreshing while on the user settings page signs the user out

### ISSUE THREAD

**Issue by Tryptophan** [gatsby-tv/gatsby#44]

**Comment by cjayross** [comment]
Woah, really? That is *wierd*. I'm setting this to high priority.

**Comment by cjayross** [comment]
Could you provide more details on how to reproduce this?

**Comment by Tryptophan** [comment]
You can check on staging, sign in with an account and go to the user settings. Refresh the page there and it will bring you back to the homepage signed out.

**Comment by Tryptophan** [comment]
Closing, this is related to load balancing, see provisioning#36
